<?php

return [
    'web' => [
        'css' => [
            '<link rel="stylesheet" href="{assets_path}/fonts/fontawesome.css" />',
            '<link rel="stylesheet" href="{assets_path}/fonts/tabler-icons.css" />',
            '<link rel="stylesheet" href="{assets_path}/fonts/flag-icons.css" />',            
            '<link rel="stylesheet" href="{assets_path}/vendors/bootstrap/css/bootstrap.min.css?100" />',
            '<link rel="stylesheet" href="{assets_path}/css/animate.css" />',
            '<link rel="stylesheet" href="{assets_path}/css/main.css" />',
            '<link rel="stylesheet" href="{assets_path}/vendors/swiper/swiper-bundle.min.css" />',
            '<link rel="stylesheet" href="{assets_path}/vendors/intl-tel-input/intlTelInput.css" />',
            '<link rel="stylesheet" href="https://cdn.plyr.io/3.7.8/plyr.css" />',
            '<link rel="stylesheet" href="{assets_path}/vendors/bootstrap-datepicker/bootstrap-datepicker.css" />',
        ],
        'js' => [
            '<script src="{assets_path}/vendors/jquery/jquery.js"></script>',
            '<script src="{assets_path}/vendors/bootstrap/js/bootstrap.bundle.min.js"></script>',
            '<script src="{assets_path}/vendors/cookie/jquery.cookie.js"></script>',
            '<script src="{assets_path}/vendors/maskedinput/maskedinput.min.js"></script>',
            '<script src="{assets_path}/vendors/uniselect/uniselect.js"></script>',
            '<script src="{assets_path}/vendors/ckeditor5-inline/ckeditor.min.js"></script>',    
            '<script src="{assets_path}/js/main.js" type="module" ></script>',  
            '<script src="{assets_path}/js/chat.js" type="module" ></script>',
            '<script src="{assets_path}/js/cart.js" type="module" ></script>',
            '<script src="{assets_path}/js/geo.js" type="module" ></script>',
            '<script src="{assets_path}/js/uniAttachFiles.js" type="module" ></script>',
            '<script src="{assets_path}/js/auth.js" type="module" ></script>',
            '<script src="{assets_path}/js/stories.js" type="module" ></script>',
            '<script src="{assets_path}/vendors/intl-tel-input/intlTelInput.min.js"></script>',
            '<script src="{assets_path}/js/uniMediaSliderModal.js" type="module" ></script>',
            '<script src="{assets_path}/vendors/sortable/sortable.min.js"></script>',
            '<script src="{assets_path}/vendors/moment/moment.js"></script>',
            '<script src="{assets_path}/vendors/swiper/swiper-bundle.min.js"></script>',
            '<script src="{assets_path}/vendors/jquery.number.min.js"></script>',
            '<script src="https://cdn.plyr.io/3.7.8/plyr.js"></script>',
            '<script src="{assets_path}/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>',
            '<script src="{assets_path}/vendors/bootstrap-datepicker/locales/bootstrap-datepicker.ru.min.js"></script>',
        ],
    ],
    'dashboard' => [
        'css' => [
            '<link rel="stylesheet" href="{assets_path}/fonts/fontawesome.css" />',
            '<link rel="stylesheet" href="{assets_path}/fonts/tabler-icons.css" />',
            '<link rel="stylesheet" href="{assets_path}/fonts/flag-icons.css" />',
            '<link rel="stylesheet" href="{assets_path}/vendors/bootstrap/css/bootstrap.min.css" />',
            '<link rel="stylesheet" href="{assets_path}/vendors/perfect-scrollbar/perfect-scrollbar.css" />',
            '<link rel="stylesheet" href="{assets_path}/vendors/bootstrap-select/bootstrap-select.css" />',
            '<link rel="stylesheet" href="{assets_path}/vendors/swiper/swiper-bundle.min.css" />',
            '<link rel="stylesheet" href="{assets_path}/vendors/apexcharts/apexcharts.css" />',
            '<link rel="stylesheet" href="{assets_path}/vendors/toastr/toastr.css" />',
            '<link rel="stylesheet" href="{assets_path}/vendors/intl-tel-input/intlTelInput.css" />',
            '<link rel="stylesheet" href="{assets_path}/css/animate.css" />',
            '<link rel="stylesheet" href="{assets_path}/css/main.css" />',
            '<link rel="stylesheet" href="https://cdn.plyr.io/3.7.8/plyr.css" />',
        ],
        'js' => [
            '<script src="{assets_path}/vendors/jquery/jquery.js"></script>',
            '<script src="{assets_path}/vendors/bootstrap/js/bootstrap.bundle.min.js"></script>',
            '<script src="{assets_path}/vendors/perfect-scrollbar/perfect-scrollbar.min.js"></script>',
            '<script src="{assets_path}/vendors/bootstrap-select/bootstrap-select.min.js"></script>',
            '<script src="{assets_path}/vendors/cookie/jquery.cookie.js"></script>',
            '<script src="{assets_path}/vendors/sortable/sortable.min.js"></script>',
            '<script src="{assets_path}/vendors/toastr/toastr.min.js"></script>',
            '<script src="{assets_path}/vendors/apexcharts/apexcharts.min.js"></script>',
            '<script src="{assets_path}/vendors/swiper/swiper-bundle.min.js"></script>',
            '<script src="{assets_path}/vendors/jquery.number.min.js"></script>',
            '<script src="{assets_path}/vendors/intl-tel-input/intlTelInput.min.js"></script>',
            '<script src="{assets_path}/js/template.js" type="module" ></script>',
            '<script src="{assets_path}/js/uniMediaSliderModal.js" type="module" ></script>',
            '<script src="{assets_path}/vendors/moment/moment.js"></script>',
            '<script src="https://cdn.plyr.io/3.7.8/plyr.js"></script>',
            '<script src="{assets_path}/js/uniAttachFiles.js" type="module" ></script>',
        ],
    ],
];
