
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `uni_settings` (
  `id` int NOT NULL,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `value` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Дамп данных таблицы `uni_settings`
--

INSERT INTO `uni_settings` (`id`, `name`, `value`) VALUES
(1, 'project_name', 'UniBoard'),
(2, 'mailer_smtp_username', ''),
(3, 'mailer_smtp_password', ''),
(4, 'mailer_smtp_port', ''),
(5, 'mailer_smtp_secure', 'SSL'),
(6, 'mailer_smtp_host', ''),
(7, 'mailer_from_name', ''),
(8, 'mailer_from_email', ''),
(9, 'logo_main', '/storage/images/b482e70310a9378e44051bb14c790436.webp'),
(10, 'logo_emblem', '/storage/images/d8c5ad2712ff521f26c4eb285f719e9a.webp'),
(11, 'allowed_extensions_images', '[\"jpeg\",\"jpg\",\"png\",\"gif\",\"webp\",\"heic\",\"HEIC\"]'),
(12, 'favicon', '/storage/images/d8c5ad2712ff521f26c4eb285f719e9a.webp'),
(13, 'watermark_status', '1'),
(14, 'watermark_type', 'title'),
(15, 'watermark_title', 'UniBoard'),
(16, 'watermark_title_font', 'Lobster-Regular.ttf'),
(17, 'watermark_title_size', 'medium'),
(18, 'watermark_title_opacity', '80'),
(19, 'watermark_image', NULL),
(20, 'watermark_image_position', '4'),
(24, 'system_default_template_theme_color', 'light'),
(25, 'system_default_template_position_menu', 'sidebar'),
(26, 'system_default_template_direction', 'ltr'),
(28, 'project_title', 'UniBoard - Доска объявлений нового поколения'),
(29, 'contact_social_links', 'null'),
(35, 'contact_email', ''),
(36, 'contact_phone', ''),
(37, 'contact_organization_name', 'ООО &quot;СуперБоард&quot;, ОГРН: 111222333444'),
(39, 'mailer_service', NULL),
(41, 'mailer_service_api_key', NULL),
(42, 'system_timezone', '(UTC+04:00) Moscow'),
(43, 'system_default_currency', 'RUB'),
(44, 'system_currency_position', 'end'),
(45, 'access_status', '1'),
(46, 'access_action', 'redirect'),
(47, 'access_text', ''),
(48, 'access_redirect_link', ''),
(49, 'access_allowed_ip', ''),
(51, 'system_notifications_to', '[\"telegram\"]'),
(52, 'system_report_status', NULL),
(53, 'system_report_period', '24'),
(58, 'integration_map_service', 'yandex'),
(59, 'integration_map_key', NULL),
(60, 'auth_services_list', NULL),
(62, 'integration_sms_service', '1'),
(63, 'integration_sms_service_data', NULL),
(64, 'allowed_extensions_files', '[\"xlsx\",\"csv\"]'),
(65, 'crontab_time_last_execution', NULL),
(66, 'active_countries', '[\"1\"]'),
(68, 'board_cost_publication', '15'),
(72, 'shops_status', '1'),
(75, 'board_publication_moderation_status', NULL),
(76, 'board_publication_premoderation_status', '1'),
(77, 'board_publication_premoderation_conditions', '[\"email\",\"phone\",\"link\"]'),
(78, 'board_publication_forbidden_words', 'Порно, наркотики, спайсы, война, сво, политик, политика, секс, курить, водка, алкоголь'),
(79, 'board_publication_required_phone_number', '1'),
(80, 'board_publication_currency_status', '1'),
(81, 'board_publication_term_date_status', '1'),
(82, 'board_publication_term_date_default', '30'),
(83, 'board_publication_only_photos', '1'),
(85, 'board_cost_publication_type', 'free'),
(86, 'board_publication_max_length_title', '150'),
(87, 'board_publication_max_length_text', '3000'),
(88, 'board_card_price_different_currencies', '1'),
(89, 'board_card_who_phone_view', 'auth'),
(90, 'phone_confirmation_status', '1'),
(91, 'email_confirmation_status', '1'),
(92, 'registration_authorization_method', 'phone'),
(94, 'system_currency_spacing', '1'),
(96, 'integration_payment_services_active', '[\"1\"]'),
(99, 'uniid_token', ''),
(100, 'uniid_data', ''),
(101, 'board_catalog_ad_view', 'grid'),
(102, 'contact_organization_address', ''),
(103, 'confirmation_length_code', '4'),
(104, 'registration_authorization_view', 'combined'),
(105, 'system_extra_currency', '[\"USD\",\"EUR\",\"AFN\",\"RUB\"]'),
(106, 'board_publication_term_date_list', '7,14,30'),
(107, 'board_publication_max_size_image', '25'),
(108, 'board_publication_max_size_video', '50'),
(109, 'board_publication_limit_count_media', '30'),
(110, 'board_publication_add_video_status', '1'),
(111, 'system_price_reduction_status', '1'),
(112, 'system_price_separator', 'spacing'),
(113, 'system_price_fraction_separator', '.'),
(116, 'system_captcha_status', '1'),
(117, 'verification_users_status', '1'),
(118, 'verification_users_permissions', NULL),
(119, 'board_publication_min_length_title', '15'),
(120, 'board_publication_min_length_text', '15'),
(121, 'board_publication_required_email', '1'),
(122, 'board_catalog_ad_option_opening', 'blank'),
(123, 'board_publication_smart_moderation_status', '1'),
(124, 'profile_wallet_status', '1'),
(125, 'profile_wallet_min_amount_replenishment', '100'),
(126, 'profile_wallet_max_amount_replenishment', '100000'),
(127, 'paid_services_status', '1'),
(128, 'board_publication_required_contact_whatsapp', '1'),
(129, 'board_publication_required_contact_telegram', '1'),
(130, 'basket_status', '1'),
(131, 'integration_payment_service_secure_deal_active', '1'),
(132, 'secure_deal_profit_percent', '1.5'),
(133, 'reviews_publication_moderation_status', '1'),
(136, 'integration_metrics_service', NULL),
(138, 'frontend_scripts', ''),
(139, 'frontend_home_slider_categories_ids', NULL),
(140, 'shop_max_pages', '5'),
(141, 'shop_max_banners', '5'),
(142, 'shop_moderation_status', '1'),
(144, 'out_default_count_items', '52'),
(145, 'stories_max_size_image', '20'),
(146, 'stories_max_size_video', '50'),
(147, 'stories_moderation_status', NULL),
(148, 'stories_period_placement', '24'),
(149, 'stories_max_duration_image', '15'),
(150, 'stories_max_duration_video', '30'),
(151, 'allowed_templates_email_all_status', '1'),
(152, 'allowed_templates_email', 'mail.ru,yandex.ru,vk.ru'),
(153, 'allowed_templates_phone_all_status', '1'),
(154, 'allowed_templates_phone', '[\"RU\"]'),
(155, 'seo_sitemap_output', '[\"cities\",\"ads_categories\",\"ads\",\"link_filters\",\"blog_posts\",\"blog_categories\",\"pages\",\"shops\"]'),
(156, 'seo_robots_index_status', NULL),
(157, 'seo_robots_data', NULL),
(158, 'seo_robots_manual', NULL),
(159, 'registration_bonus_status', '1'),
(160, 'registration_bonus_amount', '300'),
(161, 'system_report_last_time_generation', NULL),
(162, 'system_version', '5.3'),
(163, 'system_last_update', '2025-10-08 12:59:59'),
(164, 'board_catalog_height_item', '250'),
(165, 'referral_program_status', '1'),
(166, 'referral_program_percent_award', '3'),
(167, 'board_card_who_transition_partner_link', 'auth'),
(169, 'system_report_recipients_ids', '[\"1\"]'),
(170, 'geo_autodetect', '1'),
(171, 'system_report_send_time', '15:53'),
(172, 'system_report_send_if_zero', NULL),
(173, 'uni_api_link', 'https://uni-api.com.ru'),
(174, 'integration_map_lang', 'ru_RU'),
(175, 'testdrive', '0'),
(178, 'uni_api_last_notifications', '[]'),
(179, 'default_language', 'ru'),
(180, 'multi_languages_status', '1'),
(181, 'secure_deal_auto_closing_time', '3'),
(182, 'import_upload_min_size_image', '1000'),
(183, 'license_key', NULL),
(184, 'integration_delivery_services_active', NULL),
(185, 'out_default_count_items_home', '55'),
(186, 'map_default_latitude', '37.37'),
(187, 'map_default_longitude', '-122.04'),
(188, 'out_default_count_items_blog', '30'),
(189, 'allowed_extensions_videos', '[\"mp4\", \"MOV\"]'),
(190, 'watermark_image_opacity', '80'),
(191, 'watermark_image_percent_size', '30'),
(192, 'board_ads_geo_distance', '100'),
(193, 'out_default_count_city_distance_items', '28'),
(194, 'search_stopwords', 'а,без,более,бы,был,была,были,было,быть,в,вам,вас,весь,во,вот,все,всего,всех,вы,где,да,даже,для,до,его,ее,если,есть,еще,же,за,здесь,и,из,или,им,их,к,как,ко,когда,кто,ли,либо,мне,может,мы,на,надо,наш,не,него,нее,нет,ни,них,но,ну,о,об,однако,он,она,они,оно,от,очень,по,под,при,с,со,так,также,такой,там,те,тем,то,того,тоже,той,только,том,ты,у,уже,хотя,чего,чей,чем,что,чтобы,чье,чья,эта,эти,это,я,a,an,and,are,as,at,be,but,by,for,if,in,into,is,it,no,not,of,on,or,such,that,the,their,then,there,these,they,this,to,was,will,with'),
(195, 'search_allowed_text', '1'),
(196, 'search_allowed_tables', '[\"keywords\",\"filters\",\"shops\",\"ads\"]'),
(197, 'board_publication_partner_products_active_tariffs', '1'),
(200, 'api_app_user_agreement_link', NULL),
(201, 'api_app_privacy_policy_link', NULL),
(202, 'api_app_section_download_status', '0'),
(203, 'api_app_download_only_apk', '1'),
(204, 'api_app_download_link_apk', 'https://unisite.org/storage/app/uniboard5-app.apk'),
(205, 'api_app_download_links', '{\"play_market\":\"\",\"app_store\":\"\",\"app_gallery\":\"\",\"ru_store\":\"\"}'),
(206, 'api_app_firebase_push_params', NULL),
(207, 'api_app_metrica_key', ''),
(208, 'api_app_main_page_out_content', '[{\"main_categories\":true},{\"promo_sections\":true},{\"promo_banners\":null},{\"box_registration\":true},{\"stories\":true}]'),
(209, 'api_app_main_page_tabs', '[\"recommendations\",\"fresh\",\"shops\"]'),
(210, 'api_app_main_page_slider_banners_status', '0'),
(211, 'api_app_main_page_header_banner_status', '0'),
(212, 'api_app_start_promo_banners_status', '0'),
(213, 'api_app_start_promo_banners', NULL),
(214, 'api_app_main_page_header_banner', '{\"target\":\"\",\"image_link\":\"\",\"height\":\"140\"}'),
(215, 'api_app_main_page_slider_banners', '[]'),
(216, 'api_app_main_page_registration_box', '{\"title\":\"Ваш бонус ждет вас!\",\"text\":\"Зарегистрируйтесь, чтобы получить бонус на подключение платных услуг\",\"button_text\":\"Получить бонус\"}'),
(217, 'api_app_main_page_promo_sections_status', '0'),
(218, 'api_app_main_page_promo_sections', NULL),
(219, 'api_app_main_page_promo_sections_view', 'icon_name'),
(220, 'api_app_services_pages', NULL),
(222, 'api_app_nav_bar_label_status', '0'),
(225, 'api_app_fortune_bonus_items', '0,1,3,6,10,0,20,30,50,0,70,80,150,200,220,250,300,0'),
(226, 'api_app_fortune_bonus_status', '1'),
(227, 'api_app_firebase_bearer_expires_in', NULL),
(228, 'api_app_firebase_bearer', NULL),
(229, 'api_app_project_name', 'UniBoard 5'),
(230, 'system_captcha_attempts_count', '3'),
(231, 'system_verify_attempts_count', '2'),
(232, 'system_verify_block_time', '90'),
(233, 'phone_confirmation_service', 'sms'),
(234, 'integration_messenger_service', '1'),
(235, 'profile_notifications_messenger_status', '1'),
(236, 'default_template_phone_iso', 'RU'),
(237, 'api_app_replenishment_balance_amount_list', '300,500,1000,1500,3000'),
(238, 'board_publication_required_contact_max', '1'),
(239, 'api_app_catalog_item_card', '{\"user_avatar_status\":\"1\",\"city_status\":\"1\",\"height_item_photo\":\"200\",\"height_default_card\":\"160\"}');

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `uni_settings`
--
ALTER TABLE `uni_settings`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `uni_settings`
--
ALTER TABLE `uni_settings`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=240;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
