<?php
$this->container->router->group($this->container->config->app->dashboard_alias, function($router) {

    $this->container->router->any('/countries', 'Dashboard/CountriesController@countries', ['name' => 'dashboard-countries', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->any('/country/card/:id', 'Dashboard/CountriesController@cardCountry', ['name' => 'dashboard-country-card', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->any('/country/city/:id', 'Dashboard/CountriesController@cardCity', ['name' => 'dashboard-country-city-card', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->any('/country/:id/regions', 'Dashboard/CountriesController@cardRegions', ['name' => 'dashboard-country-regions-card', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->any('/country/city/:id/metro', 'Dashboard/CountriesController@cardCityMetro', ['name' => 'dashboard-country-city-metro-card', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    
    $this->container->router->xpost('/country/delete', 'Dashboard/CountriesController@deleteCountry', ['name' => 'dashboard-country-delete', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->xpost('/country/city/delete', 'Dashboard/CountriesController@deleteCity', ['name' => 'dashboard-country-city-delete', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->xpost('/country/region/delete', 'Dashboard/CountriesController@deleteRegion', ['name' => 'dashboard-country-region-delete', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->xpost('/country/add', 'Dashboard/CountriesController@addCountry', ['name' => 'dashboard-country-add', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->xpost('/country/city/add', 'Dashboard/CountriesController@addCity', ['name' => 'dashboard-country-city-add', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->xpost('/country/region/add', 'Dashboard/CountriesController@addRegion', ['name' => 'dashboard-country-region-add', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->xpost('/country/city/district/add', 'Dashboard/CountriesController@addCityDistrict', ['name' => 'dashboard-country-city-district-add', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->xpost('/country/city/district/delete', 'Dashboard/CountriesController@deleteCityDistrict', ['name' => 'dashboard-country-city-district-delete', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->xpost('/country/city/district/load-edit', 'Dashboard/CountriesController@loadEditCityDistrict', ['name' => 'dashboard-country-city-district-load-edit', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->xpost('/country/city/district/edit', 'Dashboard/CountriesController@editCityDistrict', ['name' => 'dashboard-country-city-district-edit', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->xpost('/country/city/metro/add', 'Dashboard/CountriesController@addCityMetro', ['name' => 'dashboard-country-city-metro-add', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->xpost('/country/city/metro/delete', 'Dashboard/CountriesController@deleteCityMetro', ['name' => 'dashboard-country-city-metro-delete', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->xpost('/country/city/metro/load-edit', 'Dashboard/CountriesController@loadEditCityMetro', ['name' => 'dashboard-country-city-metro-load-edit', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->xpost('/country/city/metro/edit', 'Dashboard/CountriesController@editCityMetro', ['name' => 'dashboard-country-city-metro-edit', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->xpost('/country/load-edit', 'Dashboard/CountriesController@loadEditCountry', ['name' => 'dashboard-country-load-edit', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->xpost('/country/edit', 'Dashboard/CountriesController@editCountry', ['name' => 'dashboard-country-edit', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->xpost('/country/city/load-edit', 'Dashboard/CountriesController@loadEditCity', ['name' => 'dashboard-country-city-load-edit', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->xpost('/country/city/edit', 'Dashboard/CountriesController@editCity', ['name' => 'dashboard-country-city-edit', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->xpost('/country/region/load-edit', 'Dashboard/CountriesController@loadEditRegion', ['name' => 'dashboard-country-region-load-edit', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->xpost('/country/region/edit', 'Dashboard/CountriesController@editRegion', ['name' => 'dashboard-country-region-edit', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->xpost('/country/city/change-favorite', 'Dashboard/CountriesController@changeCityFavorite', ['name' => 'dashboard-country-city-change-favorite', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->xpost('/country/add-cities-from-list', 'Dashboard/CountriesController@addCitiesFromList', ['name' => 'dashboard-country-add-cities-from-list', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);
    $this->container->router->xpost('/country/load-countries-list', 'Dashboard/CountriesController@loadCountriesList', ['name' => 'dashboard-country-load-countries-list', 'before' => ['DashboardMiddleware', 'DashboardTranslateMiddleware'], 'route_id'=>'dashboard-countries']);

}, ['dashboard'=>true]);